### ISSUE TITLE
Upgrade support to Angular v10

### ISSUE THREAD

**Issue by arian-22** [HalitTalha/ng-material-extensions#85] opened 2020-09-10 21:51 UTC
Hi, do we have news of the support for version 10 of angular?
Thanks

**Comment by ccosmincc** [comment] 2020-09-18 06:06
Duplicate of #75

**Closed** 2020-12-29 20:18 UTC

**Comment by HalitTalha** [comment] 2020-12-29 20:19
https://github.com/HalitTalha/ng-material-extensions/pull/88#issuecomment-752226266
